-- 유저정보 테이블.
CREATE TABLE TB_USER (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    USER VARCHAR(190) NOT NULL UNIQUE,
    PASSWORD VARCHAR(190) NOT NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL
);

-- INSERT INTO TB_USER (USER, PASSWORD) VALUES ('root', PASSWORD('corechips'));
-- mysql 8 버전 이상에서는 PASSWORD() 함수를 사용할 수 없다.
INSERT INTO TB_USER (USER, PASSWORD) VALUES ('root', MD5('000000'));

-- 전시장 목록.
CREATE TABLE TB_SHOWROOM (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    NAME VARCHAR(64) NOT NULL,
    MEMO TEXT NULL,
    DATA TEXT NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL
);

-- 파일 정보.
CREATE TABLE TB_MODEL_FILE (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    EXT VARCHAR(4) NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    FULL_NAME VARCHAR(68) NOT NULL,
    DIR_PATH VARCHAR(190) NOT NULL,
    PATH VARCHAR(190) NOT NULL,
    DIR_URL VARCHAR(190) NOT NULL,
    URL VARCHAR(190) NOT NULL,
    SIZE INT UNSIGNED NOT NULL,
    MEMO TEXT NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL
);