-- 유저정보 테이블.
CREATE TABLE TB_USER (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    USER VARCHAR(190) NOT NULL UNIQUE,
    PASSWORD VARCHAR(190) NOT NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL
) ENGINE=innoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- INSERT INTO TB_USER (USER, PASSWORD) VALUES ('root', PASSWORD('corechips'));
-- mysql 8 버전 이상에서는 PASSWORD() 함수를 사용할 수 없다.
INSERT INTO TB_USER (USER, PASSWORD) VALUES ('root', MD5('000000'));

-- 전시장 목록.
CREATE TABLE TB_SHOWROOM (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    NAME VARCHAR(64) NOT NULL,
    DESCRIPTION TEXT NULL,
    LINK VARCHAR(190) NULL,
    IMG_URL VARCHAR(190) NULL,
    BGM_URL VARCHAR(190) NULL,
    CONTENT_KO TEXT NULL,
    CONTENT_EN TEXT NULL,
    DATA LONGTEXT NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL
) ENGINE=innoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 모델 파일 정보.
CREATE TABLE TB_MODEL_FILE (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    EXT VARCHAR(4) NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    FULL_NAME VARCHAR(68) NOT NULL,
    DIR_PATH VARCHAR(190) NOT NULL,
    PATH VARCHAR(190) NOT NULL,
    DIR_URL VARCHAR(190) NOT NULL,
    URL VARCHAR(190) NOT NULL,
    SIZE INT UNSIGNED NOT NULL,
    DESCRIPTION TEXT NULL,
    DATA LONGTEXT NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL
) ENGINE=innoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 상품 파일 정보.
CREATE TABLE TB_PRODUCT_FILE (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    EXT VARCHAR(4) NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    FULL_NAME VARCHAR(68) NOT NULL,
    DIR_PATH VARCHAR(190) NOT NULL,
    PATH VARCHAR(190) NOT NULL,
    SIZE INT UNSIGNED NOT NULL,
    DESCRIPTION TEXT NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL
) ENGINE=innoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 상품 다운로드 키 정보.
CREATE TABLE TB_PRODUCT_KEY (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    PRODUCT_ID BIGINT UNSIGNED NOT NULL,
    DOWNLOAD_KEY VARCHAR(190) NOT NULL,
    DESCRIPTION TEXT NULL,
    END_DATE DATE NOT NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL,

    INDEX IDX_PRODUCT_KEY (PRODUCT_ID)
) ENGINE=innoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 페이지에 사용되는 값 저장.
CREATE TABLE TB_PAGE_VARIABLE (
    SEQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    NAME VARCHAR(190) NOT NULL,
    VALUE VARCHAR(190) NULL,

    C_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    U_DATE TIMESTAMP NULL,
    D_DATE TIMESTAMP NULL,

    INDEX IDX_SYSTEM_VARIABLE (NAME)
) ENGINE=innoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO TB_PAGE_VARIABLE (NAME, VALUE) VALUES ('MAIN_SHOWROOM', '0');